### ISSUE TITLE
Question about Equatable and immutability 

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [felangel/equatable#112]
I have an object that extends Equatable but I've now decided it would be nice to have one of the instance fields be not be final so I can adjust one of these fields.

I can grasp the idea of how Equatable fields should all be final and I get the alert about this field not being final and that breaks the immutability set in Equatable.

My question is what is the best practice here? Do I need to make another object that contains these non-final fields that does not extend Equatable? Everything is working with these non-final fields but I would like to do things right.

Thanks!

**Comment by felangel** [comment]
Hi @TheMeanCanEHdian 👋 
Thanks for opening an issue!

If a class is not immutable, overloading operator == and hashCode can lead to unpredictable and undesirable behavior when used in collections. See https://dart.dev/guides/language/effective-dart/design#avoid-defining-custom-equality-for-mutable-classes for more information so it is not recommended to use Equatable with non-final fields.

I would recommend defining a `copyWith` method on the class which would allow you to create a new immutable instance rather than directly mutating a property on the class. Hope that helps 👍

**Comment by TheMeanCanEHdian** [comment]
Fantastic advice, thank you. Do you have any one-time donation options where I can drop a larger lump sum or do you prefer a sponsorship donation over time?

**Comment by felangel** [comment]
> Fantastic advice, thank you. Do you have any one-time donation options where I can drop a larger lump sum or do you prefer a sponsorship donation over time?

Thanks for your generosity! I believe you can sponsor via [github sponsors](https://github.com/sponsors/felangel) and just terminate the sponsorship after one month or you can donate one time using via [open collective](https://opencollective.com/bloc). Thanks again, I really appreciate it 🙏💙

**Comment by TheMeanCanEHdian** [comment]
I'll go with a sponsorship over time then. Thanks again.
