### ISSUE TITLE
Doesn't work with List<File> as property

### ISSUE THREAD

**Issue by DamnDaniel-98** [felangel/equatable#155]
My class wich extends Equatable has a _final List(File)_  property. When i pass this property to the _probs getter_ of my class, it says that two equal Objects aren't equal. My workaround for this is to pass  "files.map((e) => e.path).toList()," instead of just the files.

**Comment by felangel** [comment]
Hi @DamnDaniel-98 👋 
Thanks for opening an issue!

I'm guessing this is because the contents of your list do not also extend `Equatable`. Please make sure that whatever type  of object is in your list also extends `Equatable` and overrides `props`. If you're still having trouble please provide a minimal reproduction sample and I'm happy to take a look 👍
