### ISSUE TITLE
Differences in default value of `EquatableConfig.stringify` in debug/release modes can lead to unexpected issues

### ISSUE THREAD

**Issue by AhmedLSayed9** [felangel/equatable#181]
`EquatableConfig.stringify` value defaults to true in debug mode and false in release mode (Implemented at #109).

While that change helps users to know the values of the properties when debugging (like in tests), it can lead to unexpected issues when relying on the `toString` value in some real use cases (i.e: in a search by object values).

Different users had that unexpected behavior in release mode at https://github.com/AhmedLSayed9/dropdown_button2/issues/240.

imo, `EquatableConfig.stringify` should defaults to the same value in both debug/release modes to avoid such critical issues while user can override its default value when debugging.

**Comment by btrautmann** [comment]
I actually came to open this exact issue about a year ago but stopped when I saw https://github.com/felangel/equatable/issues/104 (and maybe because I was feeling lazy at the moment).

I have been bitten in production twice by the difference in behavior and I definitely agree that regardless of what the global `stringify` default _is_ (I prefer `true` personally!), it should be the same in debug and release mode.

**Comment by felangel** [comment]
Sorry to hear that! Unfortunately this would be a pretty disruptive change since it would potentially break all existing users so I'm not sure it's worth doing at this point. It's also worth noting that this is no longer an issue in v3.0.0 since Equatable will no longer touch the `toString` implementation (it's moved to `package:data_class`).

**Comment by felangel** [comment]
Going to close this for now since it is resolved in the next major version (v3.0.0) and apologies for the inconvenience!
