### ISSUE TITLE
Proposal for introducing breaking changes in the future

### ISSUE THREAD

**Issue by daniel-v** [felangel/equatable#35]
With the release of 0.6.0 and the introduction of `props` getter, we had to scramble to update the codebases we are working on across multiple projects.

These projects are in flux, changing rapidly, following 3rd party changes quick, therefore we usually don't version lock our dependencies, only around the first release. Equatable is used extensively in all of the projects. The circumstances were unfortunate, 3rd party lib upgraded to 0.6 with new features we needed. We kind of had to follow that.

With this background info, I'd like to propose, that some time before such a breaking change (even if it's just a week), release a PATCH version that could look like so:

```dart
class Equatable {
  @Deprecated('Will be removed in 0.6.0, see veryshort.url')
  Equatable();
}
```

This would generate a warning in linters, allowing allocation of time to fix it and version lock the dependency until the we can follow the changes.

**Comment by felangel** [comment]
Hi @daniel-v 👋 
Thanks for opening an issue!

I'm very sorry for the breaking change without warning/deprecation. I will be sure to add deprecation warnings when possible moving forward. The reason for not doing it this time is because the constructor is was not deprecated, it was the props injection so I didn't see a good way to give a deprecation warning to only those who were using the old syntax

Also, I would highly recommend specifying `^0.6.0` in your pubspec because it should prevent you from unintentionally pulling in new major versions with breaking changes while still giving you minor fixes and improvements automatically.

Sorry again for the inconvenience and please let me know if you have any other concerns or have questions about migrating to 0.6.0 👍
