### ISSUE TITLE
Remove @immutable

### ISSUE THREAD

**Issue by jasin755** [felangel/equatable#61]
Please remove `@immutable` It has nothing to do with equatable/ comparing values.

**Comment by Yash2711** [comment]
@felangel any plan on working on this issue?

**Comment by felangel** [comment]
@jorgecoca what are your thoughts on this? While in most cases `Equatable` is used with the goal of getter closer to [data classes](https://kotlinlang.org/docs/reference/data-classes.html), it isn't technically a responsibility of the package itself to enforce this since the package is just concerned with implementing value equality. I'm not opposed to removing the immutable annotation but want to get your thoughts 👍

**Comment by jorgecoca** [comment]
Yes, I guess it makes sense; I'd ok with the change as well.

**Comment by felangel** [comment]
On second thought it doesn't appear to be a good idea because it's not recommended to override `==` and `hashCode` on classes that aren't immutable.

> If a class is not immutable, overloading operator == and hashCode can lead to unpredictable and undesirable behavior when used in collections. See https://dart.dev/guides/language/effective-dart/design#avoid-defining-custom-equality-for-mutable-classes for more information.

Going to close this for now but if you disagree feel free to comment and I'm happy to continue the discussion 👍
